export enum AuthConstants {
  CREATE_USER_START = "CREATE_USER_START",
  CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL = "CREATE_USER_FAIL",
  LOGIN_START = "LOGIN_START",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  FORGET_PASSWORD_START = "FORGET_PASSWORD_START",
  FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS",
  FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL",
}
