export enum CartConstants {
  ADD_TO_CART_START = "ADD_TO_CART_START",
  ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL",
  GET_CART_START = "GET_CART_START",
  GET_CART_SUCCESS = "GET_CART_SUCCESS",
  GET_CART_FAIL = "GET_CART_FAIL",
  REMOVE_FROM_CART_START = "REMOVE_FROM_CART_START",
  REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL",
  CLEAR_CART = "CLEAR_CART",
}
