export enum OrdersConstants {
  GET_MY_ORDERS_START = "GET_MY_ORDERS_START",
  GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS",
  GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL",
  GET_ORDERS_START = "GET_ORDERS_START",
  GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS",
  GET_ORDERS_FAIL = "GET_ORDERS_FAIL",
}
