export enum ProductConstants {
  CREATE_PRODUCT_START = "CREATE_PRODUCT_START",
  CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL",

  DELETE_PRODUCT_START = "DELETE_PRODUCT_START",
  DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL",

  GET_TOP_PRODUCTS_START = "GET_TOP_PRODUCTS_START",
  GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCTS_SUCCESS",
  GET_TOP_PRODUCTS_FAIL = "GET_TOP_PRODUCTS_FAIL",

  GET_PRODUCTS_START = "GET_PRODUCTS_START",
  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL",

  GET_PRODUCT_START = "GET_PRODUCT_START",
  GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL",

  CLEAR_PRODUCT = "CLEAR_PRODUCT",

  GET_CATEGORIES_START = "GET_CATEGORIES_START",
  GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL",

  ADD_REVIEW_START = "ADD_REVIEW_START",
  ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS",
  ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL",
}
