export enum ProductConstants {
  CREATE_PRODUCT_START = "CREATE_PRODUCT_START",
  CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL",

  GET_TOP_PRODUCTS_START = "GET_TOP_PRODUCTS_START",
  GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCTS_SUCCESS",
  GET_TOP_PRODUCTS_FAIL = "GET_TOP_PRODUCTS_FAIL",

  GET_PRODUCTS_START = "GET_PRODUCTS_START",
  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL",

  GET_CATEGORIES_START = "GET_CATEGORIES_START",
  GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL",
}
