export enum UserConstants {
    GET_USERS_START = "GET_USERS_START",
    GET_USERS_SUCCESS = "GET_USERS_SUCCESS",
    GET_USERS_FAIL = "GET_USERS_FAIL",

    GET_USER_START = "GET_USER_START",
    GET_USER_SUCCESS = "GET_USER_SUCCESS",
    GET_USER_FAIL = "GET_USER_FAIL",

    EDIT_USER_START = "EDIT_USER_START",
    EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS",
    EDIT_USER_FAIL = "EDIT_USER_FAIL",
}